#### 主要内容：
* 基本语法（基础知识、分支与循环结构、函数）
* 常用库的使用（NumPy、Pandas）

# 一、基本语法

## 1. 基础知识

In [4]:
#1. 变量的定义与赋值
a = 3
b = '量化交易'
c = True
print(a, b, c)

3 量化交易 True


In [12]:
#2. 基本运算
x1 = 3
x2 = 2
print(x1 + x2)
print(x1 * x2)
print(x1 ** x2)
print(x1 / x2)
print(x1 // x2)

5
6
9
1.5
1


In [13]:
#字符串
x3 = '量化交易'
x4 = '协会'
x5 = '第一次内培'
print(x3 + x4 + x5)

量化交易协会第一次内培


In [15]:
#3. 基本的数据结构
#1) 列表（list）
list1 = [1, '我', True, 1.2345]

In [17]:
#列表的一些常用操作
len(list1)

4

In [20]:
i = list1[0]
j = list1[-1]
print(i, j)

1 1.2345


In [19]:
list1[:2]

[1, '我']

In [21]:
list1 * 2

[1, '我', True, 1.2345, 1, '我', True, 1.2345]

In [22]:
list1 + [1, 2]

[1, '我', True, 1.2345, 1, 2]

In [35]:
#append()和extend()
w = ['量化交易']
y = [1, 2, 3, 4, 5678]
z = ['a', 'b', 'c']

In [36]:
w.append(y)
print(w)

['量化交易', [1, 2, 3, 4, 5678]]


In [37]:
y.extend(z)
print(y)

[1, 2, 3, 4, 5678, 'a', 'b', 'c']


In [40]:
#2) 字典(dict)
A = {'a': 1, 'b': 2, 'c': 3}

In [41]:
A

{'a': 1, 'b': 2, 'c': 3}

In [45]:
A['a']

1

In [51]:
list(A.values())

[1, 2, 3]

In [52]:
list(A.keys())

['a', 'b', 'c']

## 2. 分支与循环结构

In [1]:
#分支结构（if-else语句）
price = 30
cost = 25
if price >= cost:
    profit = price - cost
    print("我赚了{}块钱。".format(profit))
else:
    loss = cost - price
    print("我亏了{}块钱。".format(loss))

我赚了5块钱。


In [4]:
#注意缩进
x = 2
if x > 3:
    print('x is bigger than 3.')
print('x =', x)

x = 2


In [6]:
#循环结构（while循环和for循环）
#while循环
s = 1
while s <= 3:
    print('s =', s)
    s += 1

s = 1
s = 2
s = 3


In [7]:
#for循环
for s in range(1, 4):
    print('s =', s)

s = 1
s = 2
s = 3


In [16]:
#break与continue
for i in range(3, 9):
    if(i == 5):
        break;
    print('i =', i)

i = 3
i = 4


In [17]:
for i in range(3, 9):
    if(i == 4):
        continue;
    print('i =', i)

i = 3
i = 5
i = 6
i = 7
i = 8


## 3. 函数

In [20]:
def cay(x, y, z=0):
    result = x ** 2 + y ** 3 - z ** 4
    print('x = {}, y = {}, z = {}'.format(x, y, z))
    return result

In [21]:
cay(1, 2)

x = 1, y = 2, z = 0


9

In [22]:
cay(1, 2, 3)

x = 1, y = 2, z = 3


-72

# 二. 常用库的使用

## 1. NumPy

In [23]:
#导入numpy
import numpy as np

In [28]:
#创建数组
array1 = np.array([1, 2, 3, 4, 5])
array1

array([1, 2, 3, 4, 5])

In [69]:
len(array1)

5

In [29]:
array2 = np.arange(20).reshape(4, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
#基本操作
array2 ** 2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361]], dtype=int32)

In [31]:
array2 * 1.5

array([[ 0. ,  1.5,  3. ,  4.5,  6. ],
       [ 7.5,  9. , 10.5, 12. , 13.5],
       [15. , 16.5, 18. , 19.5, 21. ],
       [22.5, 24. , 25.5, 27. , 28.5]])

In [32]:
#广播特性
array1 + array2

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14],
       [11, 13, 15, 17, 19],
       [16, 18, 20, 22, 24]])

In [36]:
#切片
array2[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
array2[1:3, 2:3]

array([[ 7],
       [12]])

In [35]:
array2[1:3, :-1]

array([[ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [60]:
#统计特性
print(np.mean(array2))
print(np.mean(array2, axis=0))
print(np.mean(array2, axis=1))
print(np.std(array2, axis=0))

9.5
[ 7.5  8.5  9.5 10.5 11.5]
[ 2.  7. 12. 17.]
[5.59016994 5.59016994 5.59016994 5.59016994 5.59016994]


## 2. Pandas

In [38]:
#导入pandas
import pandas as pd

In [39]:
#读入excel
path = r'D:\caoxiaolong\内培\招新笔试题\return_daily.xlsx'
data = pd.read_excel(path)

In [42]:
#一些基本操作
data.head()

return
2013-04-01  0.013419
2013-04-02  0.002452
2013-04-03  0.000489
2013-04-08 -0.025428
2013-04-09  0.000502

In [43]:
data.shape

(550, 1)

In [70]:
len(data)

550

In [47]:
data.values

array([[ 0.01341948],
       [ 0.00245218],
       [ 0.00048924],
       [-0.02542787],
       [ 0.00050176],
       [-0.02708124],
       [ 0.00051546],
       [-0.02627512],
       [-0.01798942],
       [ 0.01023707],
       [-0.01386667],
       [ 0.03299081],
       [ 0.05968586],
       [-0.00049407],
       [-0.05684627],
       [ 0.01677149],
       [-0.02938144],
       [-0.00690388],
       [ 0.01122995],
       [ 0.0433633 ],
       [ 0.02939686],
       [-0.00295421],
       [ 0.00641975],
       [-0.01226693],
       [ 0.00298063],
       [-0.01337296],
       [-0.03162651],
       [ 0.0005184 ],
       [ 0.05233161],
       [ 0.00393895],
       [ 0.02893575],
       [ 0.00571973],
       [ 0.0028436 ],
       [-0.03024575],
       [ 0.0082846 ],
       [-0.01304978],
       [ 0.05778648],
       [-0.01481481],
       [-0.0037594 ],
       [-0.00990566],
       [-0.00381134],
       [ 0.01052128],
       [-0.01514434],
       [-0.0326766 ],
       [-0.02980626],
       [-0

In [45]:
data['return'].head()

2013-04-01    0.013419
2013-04-02    0.002452
2013-04-03    0.000489
2013-04-08   -0.025428
2013-04-09    0.000502
Name: return, dtype: float64

In [46]:
data.iloc[:3, :]

return
2013-04-01  0.013419
2013-04-02  0.002452
2013-04-03  0.000489

In [53]:
data.loc['2013-04-01': '2013-04-08', :]

return
2013-04-01  0.013419
2013-04-02  0.002452
2013-04-03  0.000489
2013-04-08 -0.025428

In [65]:
#统计特性
data.mean(axis=0)

return    0.001207
dtype: float64

In [67]:
data.std()

return    0.024901
dtype: float64